exports.currencyData = [
  {
    id: 1,
    symbol: "usd",
    name: "US Dollar",
    is_fiat: 1,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: null,
    precision: 8,
    ascii_sign: "$",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: null,
    code: "usd",
    currency: "usd",
  },
  {
    id: 2,
    symbol: "btc",
    name: "Bitcoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "B",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Bitcoin",
    code: "btc",
    currency: "btc",
  },
  {
    id: 5,
    symbol: "eth",
    name: "Ethereum",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 2,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "eth",
    currency: "eth",
  },
  {
    id: 6,
    symbol: "ltc",
    name: "Litecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 6,
    precision: 8,
    ascii_sign: "Ł",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Litecoin",
    code: "ltc",
    currency: "ltc",
  },
  {
    id: 7,
    symbol: "bch",
    name: "Bitcoin Cash",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 6,
    precision: 8,
    ascii_sign: "B",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Bitcoin Cash",
    code: "bch",
    currency: "bch",
  },
  {
    id: 9,
    symbol: "bsv",
    name: "Bitcoin Satoshi Vision",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 100,
    precision: 8,
    ascii_sign: "B",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Bitcoin Satoshi Vision",
    code: "bsv",
    currency: "bsv",
  },
  {
    id: 10,
    symbol: "etc",
    name: "Ethereum Classic",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 72,
    precision: 8,
    ascii_sign: "E",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum Classic",
    code: "etc",
    currency: "etc",
  },
  {
    id: 11,
    symbol: "rvn",
    name: "Raven",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 60,
    precision: 8,
    ascii_sign: "ɍ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ravencoin",
    code: "rvn",
    currency: "rvn",
  },
  {
    id: 12,
    symbol: "bat",
    name: "Basic Attention Token",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 5,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "bat",
    currency: "bat",
  },
  {
    id: 13,
    symbol: "zrx",
    name: "0x",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 5,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "zrx",
    currency: "zrx",
  },
  {
    id: 18,
    symbol: "pax",
    name: "Paxos",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "pax",
    currency: "pax",
  },
  {
    id: 31,
    symbol: "link",
    name: "Chainlink",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 1,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "₮",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "link",
    currency: "link",
  },
  {
    id: 32,
    symbol: "usdt",
    name: "Tether Stablecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 2,
    precision: 8,
    ascii_sign: "?",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "usdt",
    currency: "usdt",
  },
  {
    id: 33,
    symbol: "usdc",
    name: "USDC Stablecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 2,
    precision: 8,
    ascii_sign: "$",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "usdc",
    currency: "usdc",
  },
  {
    id: 34,
    symbol: "busd",
    name: "Binance USD",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "busd",
    currency: "busd",
  },
  {
    id: 38,
    symbol: "doge",
    name: "Dogecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 60,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Dogecoin",
    code: "doge",
    currency: "doge",
  },
  {
    id: 45,
    symbol: "fil",
    name: "Filecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.5,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Filecoin",
    code: "fil",
    currency: "fil",
  },
  {
    id: 46,
    symbol: "sol",
    name: "Solana",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.02,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Solana",
    code: "sol",
    currency: "sol",
  },
  {
    id: 47,
    symbol: "dot",
    name: "Polkadot",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 1.5,
    confirmations_needed: 25,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Polkadot",
    code: "dot",
    currency: "dot",
  },
  {
    id: 48,
    symbol: "uni",
    name: "Uniswap",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 1,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: null,
    code: "uni",
    currency: "uni",
  },
  {
    id: 49,
    symbol: "matic",
    name: "Polygon",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 20,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "matic",
    currency: "matic",
  },
  {
    id: 50,
    symbol: "avax",
    name: "Avalanche",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.1,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Avalanche",
    code: "avax",
    currency: "avax",
  },
  {
    id: 51,
    symbol: "atom",
    name: "Cosmos",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.5,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Cosmos",
    code: "atom",
    currency: "atom",
  },
  {
    id: 52,
    symbol: "aave",
    name: "Aave",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.04,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "aave",
    currency: "aave",
  },
  {
    id: 53,
    symbol: "suku",
    name: "SUKU",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "suku",
    currency: "suku",
  },
  {
    id: 54,
    symbol: "sushi",
    name: "SushiSwap",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 4,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "sushi",
    currency: "sushi",
  },
  {
    id: 55,
    symbol: "sand",
    name: "The Sandbox",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 6,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "sand",
    currency: "sand",
  },
  {
    id: 58,
    symbol: "shib",
    name: "Shiba Inu",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 500000,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "shib",
    currency: "shib",
  },
  {
    id: 59,
    symbol: "mana",
    name: "Decentraland",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 2.5,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "mana",
    currency: "mana",
  },
  {
    id: 60,
    symbol: "mob",
    name: "Mobilecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.01,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Mobilecoin",
    code: "mob",
    currency: "mob",
  },
  {
    id: 61,
    symbol: "gala",
    name: "Gala",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 100,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "gala",
    currency: "gala",
  },
  {
    id: 62,
    symbol: "yfi",
    name: "Yearn Finance",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "yfi",
    currency: "yfi",
  },
  {
    id: 63,
    symbol: "near",
    name: "Near Protocol",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.25,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Near Protocol",
    code: "near",
    currency: "near",
  },
  {
    id: 66,
    symbol: "algo",
    name: "Algorand",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Algorand",
    code: "algo",
    currency: "algo",
  },
  {
    id: 67,
    symbol: "ftm",
    name: "Fantom",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 20,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Fantom",
    code: "ftm",
    currency: "ftm",
  },
  {
    id: 72,
    symbol: "xtz",
    name: "Tezos",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 1,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "?",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Tezos",
    code: "xtz",
    currency: "xtz",
  },
];
