exports.currencyData = [
  {
    id: 1,
    symbol: "usd",
    name: "US Dollar",
    is_fiat: 1,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: null,
    precision: 8,
    ascii_sign: "$",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: null,
    code: "usd",
    currency: "usd",
  },
  {
    id: 2,
    symbol: "btc",
    name: "Bitcoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "B",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Bitcoin",
    code: "btc",
    currency: "btc",
  },
  {
    id: 5,
    symbol: "eth",
    name: "Ethereum",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 2,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "eth",
    currency: "eth",
  },
  {
    id: 6,
    symbol: "ltc",
    name: "Litecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 6,
    precision: 8,
    ascii_sign: "Ł",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Litecoin",
    code: "ltc",
    currency: "ltc",
  },
  {
    id: 7,
    symbol: "bch",
    name: "Bitcoin Cash",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 6,
    precision: 8,
    ascii_sign: "B",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Bitcoin Cash",
    code: "bch",
    currency: "bch",
  },
  {
    id: 9,
    symbol: "bsv",
    name: "Bitcoin Satoshi Vision",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 100,
    precision: 8,
    ascii_sign: "B",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Bitcoin Satoshi Vision",
    code: "bsv",
    currency: "bsv",
  },
  {
    id: 10,
    symbol: "etc",
    name: "Ethereum Classic",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 72,
    precision: 8,
    ascii_sign: "E",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum Classic",
    code: "etc",
    currency: "etc",
  },
  {
    id: 11,
    symbol: "rvn",
    name: "Raven",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 60,
    precision: 8,
    ascii_sign: "ɍ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ravencoin",
    code: "rvn",
    currency: "rvn",
  },
  {
    id: 12,
    symbol: "bat",
    name: "Basic Attention Token",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 5,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "bat",
    currency: "bat",
  },
  {
    id: 13,
    symbol: "zrx",
    name: "0x",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 5,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "zrx",
    currency: "zrx",
  },
  {
    id: 18,
    symbol: "pax",
    name: "Paxos",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "pax",
    currency: "pax",
  },
  {
    id: 31,
    symbol: "link",
    name: "Chainlink",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 1,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "₮",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "link",
    currency: "link",
  },
  {
    id: 32,
    symbol: "usdt",
    name: "Tether Stablecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 2,
    precision: 8,
    ascii_sign: "?",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "usdt",
    currency: "usdt",
  },
  {
    id: 33,
    symbol: "usdc",
    name: "USDC Stablecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 2,
    precision: 8,
    ascii_sign: "$",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "usdc",
    currency: "usdc",
  },
  {
    id: 34,
    symbol: "busd",
    name: "Binance USD",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "busd",
    currency: "busd",
  },
  {
    id: 38,
    symbol: "doge",
    name: "Dogecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 60,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Dogecoin",
    code: "doge",
    currency: "doge",
  },
  {
    id: 45,
    symbol: "fil",
    name: "Filecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.5,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Filecoin",
    code: "fil",
    currency: "fil",
  },
  {
    id: 46,
    symbol: "sol",
    name: "Solana",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.02,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Solana",
    code: "sol",
    currency: "sol",
  },
  {
    id: 47,
    symbol: "dot",
    name: "Polkadot",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 1.5,
    confirmations_needed: 25,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Polkadot",
    code: "dot",
    currency: "dot",
  },
  {
    id: 48,
    symbol: "uni",
    name: "Uniswap",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 1,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: null,
    code: "uni",
    currency: "uni",
  },
  {
    id: 49,
    symbol: "matic",
    name: "Polygon",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 20,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "matic",
    currency: "matic",
  },
  {
    id: 50,
    symbol: "avax",
    name: "Avalanche",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.1,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Avalanche",
    code: "avax",
    currency: "avax",
  },
  {
    id: 51,
    symbol: "atom",
    name: "Cosmos",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.5,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Cosmos",
    code: "atom",
    currency: "atom",
  },
  {
    id: 52,
    symbol: "aave",
    name: "Aave",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.04,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "aave",
    currency: "aave",
  },
  {
    id: 53,
    symbol: "suku",
    name: "SUKU",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "suku",
    currency: "suku",
  },
  {
    id: 54,
    symbol: "sushi",
    name: "SushiSwap",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 4,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "sushi",
    currency: "sushi",
  },
  {
    id: 55,
    symbol: "sand",
    name: "The Sandbox",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 6,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "sand",
    currency: "sand",
  },
  {
    id: 58,
    symbol: "shib",
    name: "Shiba Inu",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 500000,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "shib",
    currency: "shib",
  },
  {
    id: 59,
    symbol: "mana",
    name: "Decentraland",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 2.5,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "mana",
    currency: "mana",
  },
  {
    id: 60,
    symbol: "mob",
    name: "Mobilecoin",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.01,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Mobilecoin",
    code: "mob",
    currency: "mob",
  },
  {
    id: 61,
    symbol: "gala",
    name: "Gala",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 100,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "gala",
    currency: "gala",
  },
  {
    id: 62,
    symbol: "yfi",
    name: "Yearn Finance",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.001,
    confirmations_needed: 15,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Ethereum",
    code: "yfi",
    currency: "yfi",
  },
  {
    id: 63,
    symbol: "near",
    name: "Near Protocol",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 0.25,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Near Protocol",
    code: "near",
    currency: "near",
  },
  {
    id: 66,
    symbol: "algo",
    name: "Algorand",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 10,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Algorand",
    code: "algo",
    currency: "algo",
  },
  {
    id: 67,
    symbol: "ftm",
    name: "Fantom",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 20,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "Ξ",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Fantom",
    code: "ftm",
    currency: "ftm",
  },
  {
    id: 72,
    symbol: "xtz",
    name: "Tezos",
    is_fiat: 0,
    is_lending_enabled: 0,
    can_deposit: 0,
    can_withdraw: 0,
    min_withdrawal: 1,
    confirmations_needed: 1,
    precision: 8,
    ascii_sign: "?",
    contract_address: null,
    custody_enabled: 1,
    trading_enabled: 1,
    primary_network: "Tezos",
    code: "xtz",
    currency: "xtz",
  },
];

exports.currencyPairs = {
  btcusd: {
    formatted_symbol: "BTC/USD",
    symbol: "btcusd",
    base: "btc",
    quote: "usd",
  },
  ethbtc: {
    formatted_symbol: "ETH/BTC",
    symbol: "ethbtc",
    base: "eth",
    quote: "btc",
  },
  ltcbtc: {
    formatted_symbol: "LTC/BTC",
    symbol: "ltcbtc",
    base: "ltc",
    quote: "btc",
  },
  bchusd: {
    formatted_symbol: "BCH/USD",
    symbol: "bchusd",
    base: "bch",
    quote: "usd",
  },
  ethusd: {
    formatted_symbol: "ETH/USD",
    symbol: "ethusd",
    base: "eth",
    quote: "usd",
  },
  bchbtc: {
    formatted_symbol: "BCH/BTC",
    symbol: "bchbtc",
    base: "bch",
    quote: "btc",
  },
  ltcusd: {
    formatted_symbol: "LTC/USD",
    symbol: "ltcusd",
    base: "ltc",
    quote: "usd",
  },
  etcusd: {
    formatted_symbol: "ETC/USD",
    symbol: "etcusd",
    base: "etc",
    quote: "usd",
  },
  etcbtc: {
    formatted_symbol: "ETC/BTC",
    symbol: "etcbtc",
    base: "etc",
    quote: "btc",
  },
  btcpax: {
    formatted_symbol: "BTC/PAX",
    symbol: "btcpax",
    base: "btc",
    quote: "pax",
  },
  batusd: {
    formatted_symbol: "BAT/USD",
    symbol: "batusd",
    base: "bat",
    quote: "usd",
  },
  batbtc: {
    formatted_symbol: "BAT/BTC",
    symbol: "batbtc",
    base: "bat",
    quote: "btc",
  },
  zrxusd: {
    formatted_symbol: "ZRX/USD",
    symbol: "zrxusd",
    base: "zrx",
    quote: "usd",
  },
  zrxbtc: {
    formatted_symbol: "ZRX/BTC",
    symbol: "zrxbtc",
    base: "zrx",
    quote: "btc",
  },
  paxusd: {
    formatted_symbol: "PAX/USD",
    symbol: "paxusd",
    base: "pax",
    quote: "usd",
  },
  linkusd: {
    formatted_symbol: "LINK/USD",
    symbol: "linkusd",
    base: "link",
    quote: "usd",
  },
  btcusdt: {
    formatted_symbol: "BTC/USDT",
    symbol: "btcusdt",
    base: "btc",
    quote: "usdt",
  },
  ethusdt: {
    formatted_symbol: "ETH/USDT",
    symbol: "ethusdt",
    base: "eth",
    quote: "usdt",
  },
  ltcusdt: {
    formatted_symbol: "LTC/USDT",
    symbol: "ltcusdt",
    base: "ltc",
    quote: "usdt",
  },
  bchusdt: {
    formatted_symbol: "BCH/USDT",
    symbol: "bchusdt",
    base: "bch",
    quote: "usdt",
  },
  etcusdt: {
    formatted_symbol: "ETC/USDT",
    symbol: "etcusdt",
    base: "etc",
    quote: "usdt",
  },
  rvnusdt: {
    formatted_symbol: "RVN/USDT",
    symbol: "rvnusdt",
    base: "rvn",
    quote: "usdt",
  },
  usdcusdt: {
    formatted_symbol: "USDC/USDT",
    symbol: "usdcusdt",
    base: "usdc",
    quote: "usdt",
  },
  usdtusd: {
    formatted_symbol: "USDT/USD",
    symbol: "usdtusd",
    base: "usdt",
    quote: "usd",
  },
  btcusdc: {
    formatted_symbol: "BTC/USDC",
    symbol: "btcusdc",
    base: "btc",
    quote: "usdc",
  },
  ethusdc: {
    formatted_symbol: "ETH/USDC",
    symbol: "ethusdc",
    base: "eth",
    quote: "usdc",
  },
  bchusdc: {
    formatted_symbol: "BCH/USDC",
    symbol: "bchusdc",
    base: "bch",
    quote: "usdc",
  },
  usdcusd: {
    formatted_symbol: "USDC/USD",
    symbol: "usdcusd",
    base: "usdc",
    quote: "usd",
  },
  batusdc: {
    formatted_symbol: "BAT/USDC",
    symbol: "batusdc",
    base: "bat",
    quote: "usdc",
  },
  busdusd: {
    formatted_symbol: "BUSD/USD",
    symbol: "busdusd",
    base: "busd",
    quote: "usd",
  },
  dogebtc: {
    formatted_symbol: "DOGE/BTC",
    symbol: "dogebtc",
    base: "doge",
    quote: "btc",
  },
  linkbtc: {
    formatted_symbol: "LINK/BTC",
    symbol: "linkbtc",
    base: "link",
    quote: "btc",
  },
  dogeusdt: {
    formatted_symbol: "DOGE/USDT",
    symbol: "dogeusdt",
    base: "doge",
    quote: "usdt",
  },
  busdusdt: {
    formatted_symbol: "BUSD/USDT",
    symbol: "busdusdt",
    base: "busd",
    quote: "usdt",
  },
  paxusdt: {
    formatted_symbol: "PAX/USDT",
    symbol: "paxusdt",
    base: "pax",
    quote: "usdt",
  },
  batusdt: {
    formatted_symbol: "BAT/USDT",
    symbol: "batusdt",
    base: "bat",
    quote: "usdt",
  },
  zrxusdt: {
    formatted_symbol: "ZRX/USDT",
    symbol: "zrxusdt",
    base: "zrx",
    quote: "usdt",
  },
  linkusdt: {
    formatted_symbol: "LINK/USDT",
    symbol: "linkusdt",
    base: "link",
    quote: "usdt",
  },
  linkusdc: {
    formatted_symbol: "LINK/USDC",
    symbol: "linkusdc",
    base: "link",
    quote: "usdc",
  },
  ethpax: {
    formatted_symbol: "ETH/PAX",
    symbol: "ethpax",
    base: "eth",
    quote: "pax",
  },
  btcbusd: {
    formatted_symbol: "BTC/BUSD",
    symbol: "btcbusd",
    base: "btc",
    quote: "busd",
  },
  ethbusd: {
    formatted_symbol: "ETH/BUSD",
    symbol: "ethbusd",
    base: "eth",
    quote: "busd",
  },
  dogeusd: {
    formatted_symbol: "DOGE/USD",
    symbol: "dogeusd",
    base: "doge",
    quote: "usd",
  },
  filusd: {
    formatted_symbol: "FIL/USD",
    symbol: "filusd",
    base: "fil",
    quote: "usd",
  },
  solusd: {
    formatted_symbol: "SOL/USD",
    symbol: "solusd",
    base: "sol",
    quote: "usd",
  },
  solbtc: {
    formatted_symbol: "SOL/BTC",
    symbol: "solbtc",
    base: "sol",
    quote: "btc",
  },
  solusdt: {
    formatted_symbol: "SOL/USDT",
    symbol: "solusdt",
    base: "sol",
    quote: "usdt",
  },
  dotusd: {
    formatted_symbol: "DOT/USD",
    symbol: "dotusd",
    base: "dot",
    quote: "usd",
  },
  dotbtc: {
    formatted_symbol: "DOT/BTC",
    symbol: "dotbtc",
    base: "dot",
    quote: "btc",
  },
  dotusdt: {
    formatted_symbol: "DOT/USDT",
    symbol: "dotusdt",
    base: "dot",
    quote: "usdt",
  },
  uniusd: {
    formatted_symbol: "UNI/USD",
    symbol: "uniusd",
    base: "uni",
    quote: "usd",
  },
  unibtc: {
    formatted_symbol: "UNI/BTC",
    symbol: "unibtc",
    base: "uni",
    quote: "btc",
  },
  uniusdt: {
    formatted_symbol: "UNI/USDT",
    symbol: "uniusdt",
    base: "uni",
    quote: "usdt",
  },
  maticusd: {
    formatted_symbol: "MATIC/USD",
    symbol: "maticusd",
    base: "matic",
    quote: "usd",
  },
  maticbtc: {
    formatted_symbol: "MATIC/BTC",
    symbol: "maticbtc",
    base: "matic",
    quote: "btc",
  },
  maticusdt: {
    formatted_symbol: "MATIC/USDT",
    symbol: "maticusdt",
    base: "matic",
    quote: "usdt",
  },
  avaxusd: {
    formatted_symbol: "AVAX/USD",
    symbol: "avaxusd",
    base: "avax",
    quote: "usd",
  },
  avaxusdt: {
    formatted_symbol: "AVAX/USDT",
    symbol: "avaxusdt",
    base: "avax",
    quote: "usdt",
  },
  atomusd: {
    formatted_symbol: "ATOM/USD",
    symbol: "atomusd",
    base: "atom",
    quote: "usd",
  },
  atombtc: {
    formatted_symbol: "ATOM/BTC",
    symbol: "atombtc",
    base: "atom",
    quote: "btc",
  },
  atomusdt: {
    formatted_symbol: "ATOM/USDT",
    symbol: "atomusdt",
    base: "atom",
    quote: "usdt",
  },
  aaveusd: {
    formatted_symbol: "AAVE/USD",
    symbol: "aaveusd",
    base: "aave",
    quote: "usd",
  },
  aavebtc: {
    formatted_symbol: "AAVE/BTC",
    symbol: "aavebtc",
    base: "aave",
    quote: "btc",
  },
  aaveusdt: {
    formatted_symbol: "AAVE/USDT",
    symbol: "aaveusdt",
    base: "aave",
    quote: "usdt",
  },
  sukuusd: {
    formatted_symbol: "SUKU/USD",
    symbol: "sukuusd",
    base: "suku",
    quote: "usd",
  },
  sukuusdt: {
    formatted_symbol: "SUKU/USDT",
    symbol: "sukuusdt",
    base: "suku",
    quote: "usdt",
  },
  sushiusd: {
    formatted_symbol: "SUSHI/USD",
    symbol: "sushiusd",
    base: "sushi",
    quote: "usd",
  },
  sushiusdt: {
    formatted_symbol: "SUSHI/USDT",
    symbol: "sushiusdt",
    base: "sushi",
    quote: "usdt",
  },
  sandusd: {
    formatted_symbol: "SAND/USD",
    symbol: "sandusd",
    base: "sand",
    quote: "usd",
  },
  mplusd: {
    formatted_symbol: "MPL/USD",
    symbol: "mplusd",
    base: "mpl",
    quote: "usd",
  },
  xyousd: {
    formatted_symbol: "XYO/USD",
    symbol: "xyousd",
    base: "xyo",
    quote: "usd",
  },
  shibusd: {
    formatted_symbol: "SHIB/USD",
    symbol: "shibusd",
    base: "shib",
    quote: "usd",
  },
  shibusdt: {
    formatted_symbol: "SHIB/USDT",
    symbol: "shibusdt",
    base: "shib",
    quote: "usdt",
  },
  manausd: {
    formatted_symbol: "MANA/USD",
    symbol: "manausd",
    base: "mana",
    quote: "usd",
  },
  manausdt: {
    formatted_symbol: "MANA/USDT",
    symbol: "manausdt",
    base: "mana",
    quote: "usdt",
  },
  mobusd: {
    formatted_symbol: "MOB/USD",
    symbol: "mobusd",
    base: "mob",
    quote: "usd",
  },
  galausd: {
    formatted_symbol: "GALA/USD",
    symbol: "galausd",
    base: "gala",
    quote: "usd",
  },
  yfiusd: {
    formatted_symbol: "YFI/USD",
    symbol: "yfiusd",
    base: "yfi",
    quote: "usd",
  },
  nearusd: {
    formatted_symbol: "NEAR/USD",
    symbol: "nearusd",
    base: "near",
    quote: "usd",
  },
  algousd: {
    formatted_symbol: "ALGO/USD",
    symbol: "algousd",
    base: "algo",
    quote: "usd",
  },
  ftmusd: {
    formatted_symbol: "FTM/USD",
    symbol: "ftmusd",
    base: "ftm",
    quote: "usd",
  },
  rbtcusd: {
    formatted_symbol: "RBTC/USD",
    symbol: "rbtcusd",
    base: "rbtc",
    quote: "usd",
  },
  aaveusdc: {
    formatted_symbol: "AAVE/USDC",
    symbol: "aaveusdc",
    base: "aave",
    quote: "usdc",
  },
  avaxusdc: {
    formatted_symbol: "AVAX/USDC",
    symbol: "avaxusdc",
    base: "avax",
    quote: "usdc",
  },
  dotusdc: {
    formatted_symbol: "DOT/USDC",
    symbol: "dotusdc",
    base: "dot",
    quote: "usdc",
  },
  solusdc: {
    formatted_symbol: "SOL/USDC",
    symbol: "solusdc",
    base: "sol",
    quote: "usdc",
  },
  sushiusdc: {
    formatted_symbol: "SUSHI/USDC",
    symbol: "sushiusdc",
    base: "sushi",
    quote: "usdc",
  },
  uniusdc: {
    formatted_symbol: "UNI/USDC",
    symbol: "uniusdc",
    base: "uni",
    quote: "usdc",
  },
  avaxbtc: {
    formatted_symbol: "AVAX/BTC",
    symbol: "avaxbtc",
    base: "avax",
    quote: "btc",
  },
};

exports.coinbasecurrenyPairs = [
  {
    formattedSymbol: null,
    symbol: "USD-AVAX",
    base: "usd",
    quote: "avax",
  },
  {
    formattedSymbol: null,
    symbol: "USD-ZRX",
    base: "usd",
    quote: "zrx",
  },
  {
    formattedSymbol: null,
    symbol: "USD-NEAR",
    base: "usd",
    quote: "near",
  },
  {
    formattedSymbol: null,
    symbol: "USD-USDC",
    base: "usd",
    quote: "usdc",
  },
  {
    formattedSymbol: null,
    symbol: "USD-LINK",
    base: "usd",
    quote: "link",
  },
  {
    formattedSymbol: null,
    symbol: "USD-YFI",
    base: "usd",
    quote: "yfi",
  },
  {
    formattedSymbol: null,
    symbol: "USD-BTC",
    base: "usd",
    quote: "btc",
  },
  {
    formattedSymbol: null,
    symbol: "USD-BAT",
    base: "usd",
    quote: "bat",
  },
  {
    formattedSymbol: null,
    symbol: "USD-ETH",
    base: "usd",
    quote: "eth",
  },
  {
    formattedSymbol: null,
    symbol: "USD-USDT",
    base: "usd",
    quote: "usdt",
  },
  {
    formattedSymbol: null,
    symbol: "USD-SOL",
    base: "usd",
    quote: "sol",
  },
  {
    formattedSymbol: null,
    symbol: "USD-UNI",
    base: "usd",
    quote: "uni",
  },
  {
    formattedSymbol: null,
    symbol: "USD-SUSHI",
    base: "usd",
    quote: "sushi",
  },
  {
    formattedSymbol: null,
    symbol: "SUSHI-USD",
    base: "sushi",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "UNI-USD",
    base: "uni",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "SOL-USD",
    base: "sol",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "USDT-USD",
    base: "usdt",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "ETH-USD",
    base: "eth",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "BAT-USD",
    base: "bat",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "BTC-USD",
    base: "btc",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "YFI-USD",
    base: "yfi",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "LINK-USD",
    base: "link",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "USDC-USD",
    base: "usdc",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "NEAR-USD",
    base: "near",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "ZRX-USD",
    base: "zrx",
    quote: "usd",
  },
  {
    formattedSymbol: null,
    symbol: "AVAX-USD",
    base: "avax",
    quote: "usd",
  },
];
