module.exports = (app, express) => {
	const router = express.Router();
	const registration = require("./registration");
	const user = require("./user");
	const payment = require("./payment");
	const accountManagement = require("./accountManagement");
	const payout = require("./payout");
	const refund = require("./refund");
	const walletConnect = require("./walletConnect");
	const upload = require("./upload");
	const transaction = require("./transaction");
	const apiKey = require("./apiKey");
	const mesh = require("./mesh");
	const auth = require("./auth");
	const ocpp = require("./ocpp");
	const bastion = require("./bastion");
	const transactions = require("./transactions");
	const bridge = require("./bridge");
	const astra = require("./astra");
	const plaid = require("./plaid");
	const utils = require("./utils");
	const request = require("./request");
	const checkbook = require("./checkbook");
	const notification = require("./notification");


	registration(router);
	user(router);
	payment(router);
	payout(router);
	accountManagement(router);
	refund(router);
	walletConnect(router);
	upload(router);
	transaction(router);
	apiKey(router);
	mesh(router);
	auth(router);
	ocpp(router);
	bastion(router);
	transactions(router);
	bridge(router);
	astra(router);
	plaid(router);
	utils(router);
	request(router);
	checkbook(router);
	notification(router);
	app.use("/", router);
};
