const cryptoToCryptoStatusMap = {
    "NOT_INITIATED": "NOT_INITIATED",
    "INITIATED": "SUBMITTED",
    "QUEUED": "PENDING",
	"PENDING_RISK_SCREENING": "PENDING",
	"SENT": "PENDING",
	"CONFIRMED": "PENDING",
	"COMPLETE": "CONFIRMED",
	"CANCELED": "CANCELED",
	"FAILED": "FAILED",
	"DENIED": "FAILED",
	"ACCELERATED": "PENDING"
}

const cryptoToFiatStatusMap = {
	"NOT_INITIATED": "NOT_INITIATED",
    "INITIATED": "SUBMITTED_ONCHAIN",
    "QUEUED": "SUBMITTED_ONCHAIN",
	"PENDING_RISK_SCREENING": "SUBMITTED_ONCHAIN",
	"SENT": "SUBMITTED_ONCHAIN",
	"CONFIRMED": "SUBMITTED_ONCHAIN",
	"COMPLETE": "COMPLETED_ONCHAIN",
	"CANCELED": "NOT_INITIATED",
	"FAILED": "FAILED_ONCHAIN",
	"DENIED": "FAILED_ONCHAIN",
	"ACCELERATED": "SUBMITTED_ONCHAIN"
}

const feeRecordStatusMap = {
    "NOT_INITIATED": "NOT_INITIATED",
    "INITIATED": "SUBMITTED",
    "QUEUED": "PENDING",
	"PENDING_RISK_SCREENING": "PENDING",
	"SENT": "PENDING",
	"CONFIRMED": "PENDING",
	"COMPLETE": "CONFIRMED",
}

const statusMapCircle = {
    "CRYPTO_TO_CRYPTO": cryptoToCryptoStatusMap,
    "FEE": feeRecordStatusMap,
    "CRYPTO_TO_FIAT": cryptoToFiatStatusMap
}

module.exports = {
    statusMapCircle
}