const webhookEventActionType = {
    UPDATE: "UPDATE"
}

const webhookEventType = {
    "USER.STATUS": "USER.STATUS",
    "TRANSFER.CRYPTO_TO_CRYPTO": "TRANSFER.CRYPTO_TO_CRYPTO",
    "TRANSFER.CRYPTO_TO_FIAT": "TRANSFER.CRYPTO_TO_FIAT",
    "TRANSFER.FIAT_TO_CRYPTO": "TRANSFER.FIAT_TO_CRYPTO",
    "DEVELOPER.WITHDRAW.FEE_COLLECTION.CRYPTO_TO_CRYPTO": "DEVELOPER.WITHDRAW.FEE_COLLECTION.CRYPTO_TO_CRYPTO",
    "DEVELOPER.WITHDRAW.FEE_COLLECTION.CRYPTO_TO_FIAT": "DEVELOPER.WITHDRAW.FEE_COLLECTION.CRYPTO_TO_FIAT",
    "RECEIVER.STATUS": "RECEIVER.STATUS"
}


module.exports = {
    webhookEventActionType,
    webhookEventType
}