const Chain = {
	ETHEREUM_MAINNET: "ETHEREUM_MAINNET",
	OPTIMISM_MAINNET: "OPTIMISM_MAINNET",
	POLYGON_MAINNET: "POLYGON_MAINNET",
	ETHEREUM_TESTNET: "ETHEREUM_TESTNET",
	OPTIMISM_SEPOLIA: "OPTIMISM_SEPOLIA",
	POLYGON_AMOY: "POLYGON_AMOY",
}

const hifiSupportedChain = [Chain.ETHEREUM_TESTNET, Chain.POLYGON_MAINNET]


module.exports = {
	Chain,
	hifiSupportedChain
}